[package]

name = "amqp"
version = "0.0.2"
authors = ["Andrii Dmytrenko <andrey@reevoo.com>"]
# build = "build.rs"

[lib]

name = "amqp"

[dependencies.url]
git = "https://github.com/servo/rust-url.git"
