[package]

name = "amqp"
version = "0.0.3"
authors = ["Andrii Dmytrenko <andrey@reevoo.com>"]
description = "AMQP/RabbitMQ protocol client."
license = "MIT/BSD-2-Clause"
keywords = ["amqp", "rabbitmq", "queue"]
readme = "Readme.md"
# build = "build.rs"

[lib]

name = "amqp"

[dependencies.url]
git = "https://github.com/servo/rust-url.git"

[dependencies.collect]
git = "https://github.com/Gankro/collect-rs.git"
