[package]

name = "amqp"
version = "0.0.10"
authors = ["Andrii Dmytrenko <andrey@reevoo.com>"]
description = "AMQP/RabbitMQ protocol client"
repository = "https://github.com/Antti/rust-amqp"
license = "MIT/BSD-2-Clause"
keywords = ["amqp", "rabbitmq", "queue"]
readme = "Readme.md"
# build = "build.rs"

[lib]

name = "amqp"

[features]
tls = ["openssl"]
default = ["tls"]

[dependencies]
log = "*"
env_logger = "*"
byteorder = "*"
url = "*"
enum_primitive = "*"
bit-vec ="*"

[dependencies.openssl]
version = "0.6"
optional = true
features = ["tlsv1_1", "tlsv1_2"]
