[package]

name = "amqp"
version = "0.0.9"
authors = ["Andrii Dmytrenko <andrey@reevoo.com>"]
description = "AMQP/RabbitMQ protocol client"
repository = "https://github.com/Antti/rust-amqp"
license = "MIT/BSD-2-Clause"
keywords = ["amqp", "rabbitmq", "queue"]
readme = "Readme.md"
# build = "build.rs"

[lib]

name = "amqp"

[dependencies]
log = "*"
env_logger = "*"
byteorder = "*"
url = "*"
enum_primitive = "*"
bit-vec ="*"
